opentdf/platform

- service/cmd/migrate.go
- service/cmd/policy.go
- service/cmd/provisionFixtures.go
- service/cmd/provisionKeyloak.go
- service/cmd/root.go
- service/cmd/start.go
- service/internal/config/config.go
- service/pkg/server/start.go
This change introduces the ability to set the `config-key` or `config-file` as a flag when running any of the commands that require loading the config.
> feat: ability to set config key or config file from root cmd

- service/integration/config.go
- service/integration/subject_mappings_test.go
Cleaned up 
- `testifylint` 
- `containedctx` in suite struct.
-  `revive` using the `new` keyword as a var name
> chore: cleanup lint errors in subject_mapping tests

- .github/workflows/vulnerability-check.yaml
Fix path to `lib/ocrypto` in nightly build
> ci: nightly ocrypto

- README.md
CI and lint workflows will fail until linter is passing.  Removing the chiclets for now.
> docs: remove red chiclets

- Makefile
- README.md
Closes https://github.com/opentdf/platform/issues/157
Also fixes grep's missing `v` in the version output for `golangci-lint` check in `make toolcheck`
> chore(docs): fix nonexistent makefile script in readme, pre-build -> toolcheck

- sdk/auth_config.go
Fixes error ignored, followed by a panic.  This happens making a call to KAS public key.
> fix(sdk): handle err

- service/internal/security/hsm.go
- service/internal/security/standard_crypto.go
- service/kas/access/publicKey.go
- service/kas/access/publicKey_test.go
- Adds more checks to make sure the keys are non-nil when loading them
- Updates all asserts to use testify to hopefully get more detailed info on the errors, but we'll also need to update where they are created
> ci: Fix hsm panics in unit tests

- service/go.mod
- service/go.sum
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
go-jose is still pulled in by our oidc/oauth libraries, but at least we can reduce its usage in direct deps
> chore: replace go-jose with lestrrat/jwx

- lib/ocrypto/go.mod
- lib/ocrypto/go.sum
- sdk/go.sum
- sdk/nanotdf.go
- sdk/nanotdf_test.go
Now that ec_key_pair is available, add references to that functionality in nanotdf.
[PLAT-3112]
[PLAT-3112]: https://virtru.atlassian.net/browse/PLAT-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Not the end of the nanotdf support work by a longshot, but it gets the nanotdf header code that Misha wrote working and using the ec_key_pair code.
> feat(PLAT-3112): Initial consumption of ec_key_pair functions by nanotdf

- Dockerfile
The --platform in the `FROM` statement seems to cause issues building.
> ci: remove --platform from dockerfile FROM statement

- .github/workflows/nightly-build.yaml
I think we want the `--recursive` flag here to sign all multi-arch images as well within the manifest. 
```
-r, --recursive=false:
if a multi-arch image is specified, additionally sign each discrete image
```
> ci: add `--recursive` to cosign command

- service/internal/db/db.go
- service/internal/db/db_test.go
Resolves: #605
Also adds a couple tests to make sure `pgxpool.ParseConfig` doesn't throw any errors.
> fix: url encode db password field to handle special characters

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
the flag was inverted incorrectly
> fix(sdk): this (`enforceDPoP`) flag needs to be flipped

- Dockerfile
We want the `opentdf` application to be the entrypoint. This will allow to do things like 
`docker run registry.opentdf.io/platform:nightly provision keycloak`
instead of having to do 
`docker run -it registry.opentdf.io/platform:nightly opentdf  provision`
> fix: update dockerfile to leverage `ENTRYPOINT` instead of `CMD`

- .github/scripts/init-temp-keys.sh
- .github/workflows/checks.yaml
- README.md
- docker-compose.yaml
- opentdf-dev.yaml
Updates readme with instructions on how to run the platform locally without having to worry about setting up a go development environment.
> docs: how to run platform locally

- README.md
Addresses https://github.com/opentdf/platform/issues/704
Adds a flag to publish the port to the host so the platform is available to use.
> fix(documentation): Add flag to run command in instructions for "Running the Platform Locally"

- README-hsm.md
- examples/cmd/encrypt.go
- opentdf-dev.yaml
- opentdf-example-no-kas.yaml
- opentdf-example.yaml
- opentdf-with-hsm.yaml
- sdk/auth_config.go
- sdk/auth_config_test.go
- sdk/tdf.go
- service/authorization/authorization.go
- service/internal/access/pdp.go
- service/internal/security/standard_crypto.go
- service/internal/server/server.go
- service/kas/access/rewrap_test.go
- service/policy/db/migrations/20240213000000_create_attribute_fqn.md
This PR fixes several misspellings.
Since doing this work manually seems like a waste of time, you might consider introducing automation to prevent spelling errors (I make them constantly).
One automatic spell-checker is https://github.com/codespell-project/codespell .  It's very easy to run both locally and in CI, using pre-commit, e.g. the following will lint Go, Markdown, and YAML:
```yaml
repos:
-   repo: https://github.com/codespell-project/codespell
rev: v2.2.6
hooks:
- id: codespell
files: ^.*\.(go|md|yaml)$
args: ["--write-changes", "--ignore-words-list", "MYCOOLWORD,ANOTHAONE"]
```
> fix(core): Fix several misspellings 

- Makefile
When running `make go-lint` we don't get the same output as in ci. This pr comments out the `--new` and uncomments the config flag.
> chore: update makefile to match ci for golangci

- service/authorization/authorization.go
- service/internal/auth/authn.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
- Fixes several issues surfaced while fixing up client web, notably:
- work with empty attribute lists (for both subjects and objects). evaluates to 'permit' when both are empty
- remove duplicate dpop analysis code
- adds more stuff to dpop/auth context to make up for the missing re-parsing code
- implement SRT parsing correctly using dpop jwk if present and requested
> chore: rewrap fixes for client-web

- service/authorization/authorization.go
- service/health/health.go
- service/health/health_test.go
- service/kas/access/provider.go
- service/kas/kas.go
- service/pkg/server/services.go
- service/pkg/serviceregistry/serviceregistry.go
- service/policy/namespaces/namespaces.go
This pr introduces the ability for services to register with a centralized platform health check. 
```mermaid
block-beta
columns 1
HC["Platform Health Check"]
space
block:ID
K["KAS"]
A["Authorization Service"]
P["Policy Service"]
end
K --> HC
A --> HC
P --> HC
```
Resolves 
- #700 
- #727 
- #726
> fix(core): rollup readiness checks to central health service

- service/internal/auth/authn.go
- service/kas/access/rewrap_test.go
This would otherwise only be added if DPoP passes. However, DPoP is not required, so this would break some rewrap flows (and other services that need to inspect the JWT) when DPoP is disabled.
> fix(authz): Adds jwt to context when verified

- Makefile
- breaks down existing `make fix`, into separate `tidy` and `fmt` targets
- `make tidy` runs `go mod tidy` on all mods
- `make fmt` runs the `goimports` formatter on all .go files
- While I'm here, also assert that goimports is installed as a precondition
> chore(core): Creates make tidy and fmt targets

- .github/scripts/work-init.sh
- .github/workflows/checks.yaml
Most of our tests currently use the go workspaces feature, which allows us to test with internal 'head' (unreleased) versions of the code in sync. However. our current build infra generates per-module tags and releases, which means we need to make sure that downstream users get a coherent set of modules.
To validate a release, this removes the 'upstream' deps from the go.work before running any test. This only happens on release branches
> chore(ci): Validates internal deps are up-to-date

- .github/scripts/work-init.sh
- Remove set -e, which is in conflict with how I've been writing these scripts
- Instead, use && to leave return value set to error state if any phase fails
> chore(ci): fixes for partial workspace init

- .github/workflows/checks.yaml
- Lets the 'current' module be added for linting and unit tests only.
- Tests of other modules still use the reduced go.work
- Disables the fmt and mod tidy up to date checks on release branches
> chore(ci): Fixes issue with lint in releases

- service/authorization/authorization.go
AuthorizationService had no tokenSource or logger causing panics from nil pointer exceptions.
This PR returns the correct AuthorizationService with a provided logger.
> fix(core): wrong AuthorizationService provided with missing logger

- README.md
- service/README.md
Refactored the docs to reduce the overhead on the top-level (monorepo) README. Extrapolated on the audience direction (Consumer and Contributor) that @dmihalcik-virtru mapped out.
Moved service details under the `./service/README.md` and added a top-level Quick Start for Consumers.
> chore(docs): improve developer docs

- docs/configuration.md
- opentdf-dev.yaml
- opentdf-example-no-kas.yaml
- opentdf-example.yaml
- opentdf-with-hsm.yaml
- service/internal/security/hsm.go
- service/internal/server/server.go
- service/kas/access/publicKey_test.go
Tries to cleanup the `cryptoProvider` configuration by removing the redundant fields of `hsm.enabled` and `cryptoProvider.type`.
> fix(service): cleanup the cryptoprovider config

- .github/scripts/init-temp-keys.cmd
Windows script for temp keys generation. It's just a copy of the existing shell script for temp keys generation. Our team cannot use existing shell script, because we are using Windows.
> chore(main): Temp keys generation script for Windows

- README.md
- service/README.md
In README.md files, changed mention of docker-compose.yml -> docker-compose.yaml to match the actual filename.
> chore(docs): Fix typo in README files

- CODEOWNERS
- These are often updated for dep updates that may be needed for releases
- We assume people will use their best judgement when adding new dependencies, and we should audit *all* dependencies on some schedule anyway
> chore(core): Allows maintainers to approve go.mod

- .gitignore
- service/internal/security/crypto_provider.go
- service/internal/security/hsm.go
- service/internal/security/standard_crypto.go
- service/kas/access/provider.go
- service/kas/access/publicKey.go
- service/kas/access/rewrap.go
- service/kas/kas.go
Legacy clients, client-web and client-cpp, use this endpoint and expect a certificate.
Modified the handling of ECC keys by adding a certificate method for ECC. Enhanced readiness checks in the Provider struct by adding Config property. Updated rewrap function to log errors and responses for both 'tdf3' and 'nano' procedures. Also, updated the .gitignore file to ignore 'sensitive.txt.ntdf'.
> feat(kas): add certificate to legacy rest endpoint

- .github/workflows/checks.yaml
- examples/cmd/decrypt.go
- examples/cmd/encrypt.go
- opentdf-dev.yaml
- sdk/kas_client.go
- sdk/nanotdf.go
- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/security/hsm.go
- service/internal/security/standard_crypto.go
> salt - This is a non-random value tied to the magic number and version SHA256(MAGIC_NUMBER + VERSION). So for this version of the nanotdf the value of the salt is 3de3ca1e50cf62d8b6aba603a96fca6761387a7ac86c3d3afe85ae2d1812edfc in hex.
source: https://github.com/opentdf/spec/tree/main/schema/nanotdf#4-ecc-encryption-key-derivation
> fix(core): Update hkdf salt

- .github/workflows/release.yaml
First, use the release please step to determine if a release was created. If a library was released, build its list of downstream deps (hard coded for now, could be queried with a script). Then, trigger another job that updates those deps and builds a PR that updates them
Issue: https://github.com/opentdf/platform/issues/839
> chore(ci): Updates deps after release is tagged

- .github/workflows/release.yaml
`chore` indicates no user visible change
Use `fix`, since these will cause changes downstream
> chore(ci): Commits with bumps should be fixes

- lib/fixtures/keycloak.go
- opentdf-dev.yaml
- opentdf-example.yaml
- opentdf-with-hsm.yaml
- sdk/internal/oauth/oauth_test.go
- service/cmd/keycloak_data.yaml
- service/internal/auth/authn_test.go
- service/internal/auth/casbin.go
- service/internal/auth/casbin_test.go
Resolves https://github.com/opentdf/platform/issues/928
Rename `readonly` base casbin policy role in route auth middleware to `standard` to reflect that there are base _write_ routes like `/kas/v2/rewrap` that should not be gated to admins and should not be read only (POST method over REST).
> fix(core): update default casbin auth policy

- .github/workflows/checks.yaml
- service/internal/security/standard_crypto.go
- service/kas/access/publicKey.go
- service/kas/access/publicKey_test.go
Updates kas_public_key endpoints to return a 404 instead of a 500 if the public key lookup fails. Potential ways a public key is not found:
1. unsupported algorithm
2. unrecognized key identifier (either user supplied TK or default)
This will still 500 on errors in config format or key format
TK should also return 400 on invalid fmt
> fix(core): Return 404 if public key not found

- service/internal/auth/casbin.go
Defining the `/healthz` endpoint isn't necessary as its a public endpoint and doesn't need to be controlled by casbin.
https://github.com/opentdf/platform/blob/687e4bdc0d90f7b689b74dc100b0514cc959eb43/service/internal/auth/authn.go#L41-L49
Resolves #905
> fix(core): remove /health from casbin default policy

- service/internal/auth/authn.go
- service/internal/auth/casbin.go
We bypass all auth on public routes so they don't need to be defined in casbin. 
https://github.com/opentdf/platform/blob/5e214683c2c219e60768862cc23de22678ef855a/service/internal/auth/authn.go#L154-L159
https://github.com/opentdf/platform/blob/5e214683c2c219e60768862cc23de22678ef855a/service/internal/auth/authn.go#L218-L222
> fix(core): remove public routes from casbin default policy

- service/internal/config/config.go
- service/pkg/server/start.go
This flag is currently only used to signal that the helm chart was deployed with the embedded keycloak and postgres and that this is not a production deployment.
> feat: add dev_mode flag

- .github/workflows/checks.yaml
- .github/workflows/release.yaml
- To let `go mod tidy` work with new packages in downstream workspace mods, we need to insert replace directives
- However we don't want these to get tagged! To work around this:
- fail checks if on a release branch for a module that has *any* replace directives
- During dep update check, remove any replace directives for that dep.
- The dep update is a brittle - notably it doesn't support paranthesized grouping of replace directives
> chore(ci): Support go.mod replace directives

- .github/workflows/checks.yaml
- .github/workflows/release.yaml
- The `go mod edit` (and associated commands), with jq, provides more clear, and less brittle, functionality to inspect and modify replace and require directives than relying on grep, awk, etc.
> chore(ci): replaces awk with go mod edit

- service/go.mod
- service/go.sum
- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
Adds doublestar support to enable this
```
/mypep/*                         
/mypep/*/*                       
/mypep/dist/*                 
/mypep/dist/*/*
/mypep/dist/js/*
/mypep/dist/js/*/*
/mypep/dist/js/import/*
/mypep/dist/js/import/*/*
/mypep/assets/*                  
/mypep/assets/*/*
/mypep/assets/images/*
/mypep/assets/images/*/*
/mypep/assets/styles/*
/mypep/assets/styles/*/*
``` 
to this
```
/mypep/*
/mypep/*/*
/mypep/dist/**
/mypep/assets/**
```
> feat(core): add doublestar for public routes

- lib/fixtures/keycloak.go
Enable "unmanaged attributes" even if the realm already exists
resolves https://github.com/opentdf/platform/issues/994
> fix(ci): Ensure unmanaged attributes is enabled during kc provisioning

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/auth/config.go
Parsing a jwt is not a free operation and in `authn` we were first parsing the token to extract the issuer. Currently this is not necessary because we only support 1 issuer in our `authn` configuration. 
This pull request removes that unnecessary  parse call and moves to passing the keyset directly into the jwt parse call. 
The reason this came about is when we were profiling our service under load it was obvious there was some slight over head doing this twice.
> refactor(core): remove extra jwt parse from authn interceptor

- .github/workflows/release.yaml
jq 1.7.1 is fine with the `.[]` syntax but not version 1.6, which the version in the current ubuntu GitHub action runner.
Tested via running
```sh
> docker run -it --rm -v $(pwd)/:/project debian /bin/bash
> apt-get update
> apt-get install curl
> curl -L -o /usr/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64
> chmod +x /usr/bin/jq
> apt-get install golang
> cd project/sdk
> x=lib/fixtures
> export pkg=github.com/opentdf/platform/${x}
>  go mod edit --json | jq -e '.Replace.[] | select(.Old.Path == env.pkg)'
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
.Replace.[] | select(.Old.Path == env.pkg)
jq: 1 compile error
> go mod edit --json | jq -e '.Replace[] | select(.Old.Path == …
```
> chore(ci): fix jq syntax

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/server/server.go
When the platform points to an internal issuer endpoint. Example keycloak is running within a k8s cluster we should try to replace it if its different from what is returned from the  discovery endpoint.
> fix(core): swap out internal issuer for external issuer endpoint

- sdk/go.mod
- sdk/go.sum
- sdk/options.go
- sdk/sdk.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_test.go
- replaces wiremock of keycloak and well-known services with
- use traditional mocks for AccessToken
- use in-process grpc for wellknownconfig
- wiremock has been causing me lots of trouble with my colima setup
- and also most of our services are easier to mock locally anyway
> refactor(ci): Removes wiremock from sdk tests

- sdk/idp_cert_exchange.go
- sdk/internal/oauth/oauth.go
- sdk/internal/oauth/oauth_test.go
> fix: Issue #1008 : Use exchange info's TLS Configuration for cert based auth

- service/pkg/db/db_migration.go
- service/pkg/server/services.go
Closes #742 
1. Runs migrations just once and IFF at least one service requires a DB connection
2. Resolves pass by value error where struct pointer `*db.Client` outside for loop was not reassigned within `startService` function due to copy of value. Returns a `*db.Client` instead of resolving with `**db.Client` parameter for better readability.
Service starting logs after these changes:
```shell
time=2024-06-26T16:54:22.597-07:00 level=INFO msg="starting services"
time=2024-06-26T16:54:22.597-07:00 level=INFO msg="skipping migrations" namespace=wellknown service=wellknownconfiguration.WellKnownService runMigrations=true reason="service does not require a database"
time=2024-06-26T16:54:22.597-07:00 level=INFO msg="started service" namespace=wellknown …
```
> fix(policy): run migrations on db only once for all policy services

- service/integration/attributes_test.go
- service/policy/db/attribute_values.go
- service/policy/db/attributes.go
> fix(policy): provide ns and val fqns back on list attributes response

- service/pkg/db/db.go
- service/pkg/db/db_migration.go
Closes #681 
Per service with db connection:
- one client
- one schema
- one shared pool
Not supported (and documented in db package)
- multiple schemas per client
- multiple services sharing a pool (unless rolled up into one service like policy)
- multiple databases per platform Postgres instance
- multiple Postgres servers per platform instance
> fix(core): database clients pooling improvements

- Makefile
- lib/flattening/flatten_test.go
- service/internal/subjectmappingbuiltin/subject_mapping_builtin_test.go
Added benchmark tests within 'Makefile', 'flatten_test.go', and 'subject_mapping_builtin_test.go' files. The newly added benchmarks will facilitate performance testing for certain functions and services in our codebase, enabling us to spot and fix any potential performance issues.
partially resolves https://github.com/opentdf/platform/issues/785
> chore: benchmarks for authorization service

- .github/dependabot.yml
- lets gh action update messages start `chore(ci)`
> chore(ci): Improve dependabot msgs

- Makefile
use `go run X` instead of `go install X && X`
> chore(core): Don't require installing go-licenses

- .github/workflows/vulnerability-check.yaml
- go.work
This is consistent with the go.mod files and will reduce the number of toolchains local devs will install.
I updated govulncheck to use the same version as other CI actions (currently latest - maybe it should just be latest (the default - so unspecified)?)
> chore(ci): Let go.work sdk target 1.21

- service/internal/server/server.go
Exposes pprof routes so we can capture profiling information when facing a performance issue.
> chore(core): ability to turn on pprof routes 

- service/kas/access/rewrap.go
This error has been confusing for others and myself when trying to debug issues in KAS. Longer term we might want to validate the hostname but right now this has no effect.
> fix(kas): remove unused hostname check

- sdk/kas_client.go
- sdk/manifest.go
- sdk/nanotdf.go
- sdk/sdk.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_test.go
- service/kas/access/keyaccess.go
Implementation of https://github.com/opentdf/spec/pull/32
This is a proposal to allow customizing how a client shares key data across multiple KASes. With a split, you can copy the same share to multiple providers, allowing for robustness if a given KAS is unavailable - or if a decrypting user or application does not have authorization with that KAS.
> feat(sdk): Support custom key splits

- examples/cmd/encrypt.go
- sdk/README.md
- sdk/go.mod
- sdk/internal/autoconfigure/granter.go
- sdk/internal/autoconfigure/granter_test.go
- sdk/kas_client.go
- sdk/nanotdf_config.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_test.go
- test/tdf-roundtrips.bats
Allows looking up the `grants` fields of the data attributes to determine which KAS or set of KASes should be used to wrap a given document key.
Basic flow:
```go
s, err := sdk.New(/* config options */)
s.CreateTDFContext(out, in, sdk.WithDataAttributes("http://your/attr/tag/value/here"))
```
this will look up any grants associated with the policy and use them to generate a KAO that shares and/or splits the values across the given KAS elements as needed.
Note that this changes several default behaviors:
1. Use `WithAutoconfigure(false)` to disable the new attribute kas grant lookup code
2. Previously, calls to `WithDataAttribute` did no validation (would not return errors). Now they use a regex to validate the FQN format (even with autoconfigure disabled).
3. With Autoconfigure enabled, …
> feat(sdk)!: Autoconfigure with grants

- .github/workflows/checks.yaml
- examples/cmd/attributes.go
- examples/cmd/decrypt.go
- examples/cmd/encrypt.go
- examples/cmd/examples.go
- test/policy-service.bats
- test/service-start.bats
- adds tokenEndpoint and creds params to root example command
- Use the admin creds in a test instead of the 'standard' creds
- namespaces must be valid dns names
> fix(examples): let attributes example work

- service/kas/access/rewrap.go
- service/pkg/server/start.go
chore(kas): remove want log on access denied
Switches some log statements to `debug` to try and reduce more noise. Also removes the `warn` log statement on access denied decision in kas because we have audit so a user will know why a rewrap was denied.
> chore(core): set some startup logs to debug

- sdk/tdf.go
- sdk/tdf_config.go
- I'll try to replace this with a more generic cache as part of 'better offline support' work
- Also we *should* have some kind of allowlist, but we may want to do this:
-  directly on the SDK
- as middleware
> fix(sdk): Allow empty kas info list

- sdk/internal/autoconfigure/granter.go
- sdk/internal/autoconfigure/granter_test.go
- sdk/tdf.go
- sdk/tdf_test.go
- Lets autoconfigure group attributes by case insenstiive name
- This still may have bugs in case sensitive values
- And also it is case sensitive by KAS url, resulting in unnecessary splits to the same server
> fix(sdk): Remove case sensitivity of attr values

- .github/workflows/release.yaml
- auto merge PRs submitted with releases
I think that th is still may require an approving review to unblock the merge. Currently investigating if there's a way we could get around that by polssibly making @opentdf-automation a codeowner of these go mod files?
> chore: Auto Merge Release Version Bumps

- .github/workflows/auto-approve-version-bumps.yaml
Auto approves version bump PRs that satisfy the following conditions
- author is `opentdf-automation`
- PR title starts with `fix(core): Autobump`
I believe this will have the PR be approved by the GH actions bot. WE may need to add that bot as a codeowner to the mod files or maybe generate a token for a dedicated bot separate from opentdf-automation?
> chore: Auto Approve Version Bumps

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/auth/config.go
- Adds acceptable skew control to oidc configuration
- for idp provided tokens, use `skew` (default 1 minute)
- for client provided tokens (dpop tokens), use `dpopskew` (default 1 hour)
- This should reduce flakiness on some tests
> feat(core): Adds authn time skew config

- service/internal/server/server.go
Due to changes somehow related to unsafe actions, the DSP / COP function `GetMyEntitlements` (getting entitlements by access token) started failing. 
The breaking change is [here](https://github.com/opentdf/platform/commit/4a3042625d0d08951bc36053ba053dc44fcffe99#diff-6dfc9f9359c6ea6dbaf8df5306e47732e636997b51bd20ef1eaef77f6d39823dR175-R176).
Essentially, we exceeded the in process / internal grpc server's message size limit when passing attribute values in responses. Internal services should be able to communicate freely.
> fix(core): increase internal grpc message size limit

- .github/scripts/init-temp-keys.cmd
- .github/scripts/init-temp-keys.sh
- Generally, the user will already need a keycloak image, which has keytool packed in
- The `openjdk` image is unmaintained
> chore(ci): Prefer using keycloak image for keytool

- .github/workflows/stale.yaml
Resolves #1264 
- Doubles stale time from default 60 days to 120 days
- Sets job to _not_ auto-close stale issues & PRs
> fix(ci): double stale issue length and do not close issues automatically

- service/policy/db/migrations/20240806142109_add_resource_mapping_groups.md
- service/policy/db/migrations/20240806142109_add_resource_mapping_groups.sql
- service/policy/db/models.go
- service/policy/db/query.sql
- service/policy/db/query.sql.go
closes #1256 
- add migration for new `resource_mapping_groups` table and related ERD
- add basic SQL queries and `sqlc` generated functions (will be expanded on in follow-up PRs)
> feat(policy): 1256 resource mapping groups db support

- README.md
> fix(core): 1269 readme quickstart has incorrect steps

- docs/configuration.md
- service/kas/kas.go
- service/kas/kidless_test.go
- Changes 'default' behavior of `legacy` field to be true if none are specified
- This feature is a performance optimization for some imagined future when all 'new' TDFs are created with KIDs in their KAOs. We are not there yet.
- Resolves #1273
> feat(core): Simplifies support for kidless clients

- .github/workflows/pr-checks.yaml
As part of SEC-4101 & Closes #1316 I am reviewing our current dependency configurations.  Currently the PR checks are failing due to the PR using `chore(deps)` for the PR prefix.  For example: https://github.com/opentdf/platform/pull/1311
> chore(ci): SEC-4101 Update pr-checks workflow to add `deps` tag

- sdk/options.go
- sdk/platformconfig.go
- sdk/sdk.go
- service/pkg/server/start.go
Resolves: https://github.com/opentdf/platform/issues/1360
> fix(sdk): align sdk with platform modes

- .github/workflows/checks.yaml
- go.work
- service/go.mod
Resolves https://github.com/opentdf/platform/issues/1406
> fix(core): bump go version to 1.22

- service/pkg/db/db.go
- service/pkg/db/db_test.go
Resolves #1442
Instead of executing the `SET search_path` on the first connection found when a pool is instantiated, we should utilize the `AfterConnect` [PGX hook](https://github.com/jackc/pgx/blob/4f7e19d67df4d411ac1c19373390021a2f23aa07/pgxtest/pgxtest.go#L37) which exposes a connection immediately after it's opened and before it's utilized.
> fix(core): policy db should use pool connection hook to set search_path

- service/authorization/authorization.go
- service/authorization/authorization_test.go
> fix(authz): entitlements fqn casing

- README.md
schema diagram link is broken in the top level readme. Updating it to the new path. 
Fixes https://github.com/opentdf/platform/issues/1459
> chore(docs): fix broken link in readme

- service/wellknownconfiguration/wellknown_configuration.go
This small bug was found while browsing through the code base.  This PR closes #1461
> fix(core): Fix deadlock when registering config with duplicate namespace

- sdk/resource_locator.go
- sdk/resource_locator_test.go
- service/kas/access/rewrap.go
Introduced padding removal logic in the `GetIdentifier` method of `ResourceLocator` to ensure cleaned identifiers. Also changed log level from Info to Debug in `nanoTDFRewrap` for more appropriate logging detail.
resolves #1467
> fix(core): Add NanoTDF KID padding removal and update logging level

- .github/scripts/connectivity-test.sh
- .github/workflows/checks.yaml
- .github/workflows/nightly-checks.yaml
> feat(ci): nightly checks with connectivity recovery test

- lib/flattening/flatten.go
- lib/flattening/flatten_test.go
- lib/ocrypto/fuzz_test.go
- sdk/internal/oauth/oauth.go
- sdk/kas_client.go
- service/internal/subjectmappingbuiltin/subject_mapping_builtin.go
This PR includes additional fuzzing and security testing that was not covered in prior PR's (#1472 and #1385).  Those PR's include the relevant tests for their fixes, where this provides additional testing that was explored but did not show issues.
In addition this PR includes some minor changes that were found while reviewing the code base:
* Spelling fixes
* Token issue time and expiration based off the same time sample (reduced kernel overheads and also ensures no time skew risks)
PR closes #1341
> chore(sdk): Expand fuzz testing and minor spelling fixes

- sdk/granter.go
looks like previously we were only store attribute value grants to the cache
resolves https://github.com/opentdf/platform/issues/1517
> fix(core): Store attribute specific grants to key cache

- .github/workflows/checks.yaml
- .golangci.yaml
- Makefile
- sdk/internal/oauth/oauth_test.go
- service/integration/attribute_values_test.go
- service/integration/attributes_test.go
- service/integration/namespaces_test.go
- service/integration/resource_mappings_test.go
- disables new integer overflow check with too many hits
- fixes other issues
- Fixes #1409
> chore(core): Updates golangci-lint to 1.60

- test/start-additional-kas/action.yaml
- test/start-up-with-containers/action.yaml
After changes introduced in https://github.com/opentdf/tests/pull/184
Resolves https://github.com/opentdf/platform/issues/1530
Working tests in `opentdf/tests`: https://github.com/opentdf/tests/pull/190
Working tests in `opentdf/otdfctl`: https://github.com/opentdf/otdfctl/pull/369
> fix(ci): reusable plat/kas startup actions enhancements from opentdf/tests

- sdk/fuzz_test.go
- sdk/internal/archive/reader.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_config_test.go
- sdk/tdf_test.go
This fixes three DoS conditions discovered:
* Specifying a very large segment size which could result in the SDK allocating a large buffer in memory
* Specifyin a very small segment size which could result in excessive cpu and io overheads
* Specifying a size in the manifest which will overflow, resulting in a `panic` when a negative byte slice is allocated
Unit testing and fuzz testing was expanded to cover these conditions.  This PR fixes #1535
> fix(sdk): DoS protection through TDF segment sizes

- .github/scripts/metrics.js
- .github/workflows/traffic.yaml
this PR runs a workflow once a week to get Github repo traffic metrics for each of the opentdf public repos. it puts it in a gcp bucket where bigquery can be integrated. Goal is to be able to visualize the data over time to see views, referral sources, clones, etc. can be expanded in the future if we want any more info. 
https://github.com/opentdf/platform/actions/runs/10904129901
^ this was a successful run of the workflow.
> feat(ci): Get traffic metrics for OpenTDF repos 

- .github/workflows/checks.yaml
resolves https://github.com/opentdf/platform/issues/1510
> fix(ci): Don't run tests for markdown changes

- lib/ocrypto/ec_key_pair.go
- sdk/kas_client.go
- sdk/kas_client_test.go
- sdk/nanotdf.go
- sdk/nanotdf_config.go
- sdk/nanotdf_test.go
- sdk/sdk.go
- service/logger/audit/test.pb.go
- Adds new method, `sdk.SDK.StoreKASKeys` to load kas key cache
- Use the sdk's `getPublicKey` method from the nanotdf code as expected, which defers to the cache
- Removes dead or duplicated code that (tried to) do this
- Fixes https://github.com/opentdf/platform/issues/1547
> feat(sdk): Improve KAS key lookup and caching

- service/entityresolution/keycloak/keycloak_entity_resolution.go
resolves https://github.com/opentdf/platform/issues/1615
before: `jwtentity-0` or `jwtentity-1`
now includes more useful info in the entity name
```
{
"id": "jwtentity-0-clientid-tdf-entity-resolution-public",
"client_id": "tdf-entity-resolution-public",
"category": "CATEGORY_ENVIRONMENT"
},
{
"id": "jwtentity-1-username-sample-user",
"user_name": "sample-user",
"category": "CATEGORY_SUBJECT"
}
```
This is useful for parsing access decisions triggered by kas. Access decisions only reference the entityID so, previously, it was be difficult to know what entity it is referring to without looking through the rest of the logs. This change should provide more context and save debugging time.
> feat(authz): Add name to entity id when retrieved from token

- .golangci.yaml
- service/logger/audit/getDecision_test.go
- service/logger/audit/helpers_test.go
- service/logger/audit/policy_test.go
- service/logger/audit/rewrap_test.go
- service/logger/audit/utils.go
- service/logger/audit/utils_test.go
Refactored the code to directly fetch the request ID as a UUID type instead of first parsing it from a string. This change eliminates unnecessary error handling and simplifies logic for extracting the request ID from the context.z
Resolves #1489
> fix: Simplify request ID extraction from context for AUDIT

- service/internal/auth/casbin.go
Lets `standard` users retrieve authorization decisions. [Does not allow these users to retrieve entitlements](https://github.com/opentdf/platform/blob/e3ed0b5ce6039000c9e3c574d3d6ce2931781235/service/authorization/authorization.proto#L289-L305). Implements discussion from https://github.com/virtru-corp/data-security-platform/pull/403.
Resolves https://github.com/opentdf/platform/issues/1645.
> fix: allow standard users to get authorization decisions

- .github/workflows/codeql.yaml
I want to explore using CodeQL to assist as part of our static analysis strategy.  Because this tool is available for free to open source projects, `opentdf` is a good place to start this testing.
This PR adds an initial configuration which will scan the codebase once a week.  These results can be ignored for the time being.  Instead the security team will review the results and make sure we tune away any noise first (or help in opening PR's to address any valid issues found).
[SEC-4162]: https://virtru.atlassian.net/browse/SEC-4162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(ci): Add initial CodeQL Workflow

- docs/configuration.md
Updated documentation to include Casbin configuration for endpoint authorization. Added details on key aspects of authorization, example configuration, role permissions, and managing policy through the YAML file. This enhances the security and flexibility of endpoint access control.
https://github.com/opentdf/docs/issues/28
DSP-129
> chore: Casbin authorization policy configuration docs

- .github/workflows/git-town.yaml
Adding git-town workflow to do a poc around stacked prs as we migrate to connect-rpc.
https://github.com/marketplace/actions/git-town-github-action
> chore(ci): add git-town workflow

- CODEOWNERS
This reverts commit 645a52143d3443baa0729854d17d79801ed4370c.
> chore(ci): revert codeowners architecture-only during code freeze

- service/policy/adr/0003-database-transactions.md
> feat(policy): 1659 spike on transactions support

- sdk/tdf.go
reversed handling of requests
successful error detection in xtest https://github.com/opentdf/tests/actions/runs/11635869428/job/32406122022?pr=220
> fix(sdk): Fix handling of kas rewrap errors

- service/internal/fixtures/db.go
Fixes [https://github.com/opentdf/platform/security/code-scanning/7](https://github.com/opentdf/platform/security/code-scanning/7) and closes #1694
This change resolves the CodeQL alert in fixtures by ensuring that if the string contains any single quotes they are escaped using two single quotes.
> fix: Fixtures CodeQL alert for potentially unsafe quoting

- sdk/nanotdf.go
- sdk/nanotdf_test.go
This change removes two debug logs where the nanoTDF key was encoded and logged.
In addition this fixes a small 1 in 16 million chance that an all zero IV could be used on the data (resulting in a key + iv reuse when compared to the policy).
> fix: NanoTDF secure key from debug logging and iv conflict risk

- sdk/sdk.go
- sdk/sdk_test.go
> fix(sdk): reset reader after checking if IsNanoTDF

- sdk/kas_client.go
- error messages should be unique to ease debugging
> fix(sdk): Error message improvements

- service/kas/access/accessPdp.go
* only make authorization call when necessary
go sdk creates a policy object with null in the attributes field if none provided but js fills it with "[]" which still triggered an authorization call -- this change should stop that
> fix(kas): Only hit authorization if data attributes not empty

- service/health/health.go
- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/kas/access/publicKey.go
- service/wellknownconfiguration/wellknown_configuration.go
> fix: cleanup left over status.Error in favor of connect.NewError

- .github/workflows/checks.yaml
- examples/cmd/examples.go
- opentdf-dev.yaml
- service/pkg/server/services.go
- service/rttests/rt_test.go
- test/policy-service.bats
- test/rego/custom-entity.bats
- test/rego/static-entitlements.bats
- test/service-start.bats
- test/tdf-roundtrips.bats
Fixes grpc-gateway from endpoint to support tls. This was a miss on the initial pr https://github.com/opentdf/platform/pull/1733 because we don't have any tests where we enable tls. So this pull request updates the integration tests to run with tls enabled as well.
> fix: grpc-gateway connection with tls enabled

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/server/server.go
- Threads through Dpop token and  REST service path from gRPC gateway
- This is needed when DPoP is enabled (required) OR when the IdP requests it
> fix(core): Updates dpop check for connect

- docker-compose.yaml
I think the chainguard keycloak image is now private so our tests are breaking.
https://github.com/opentdf/platform/actions/runs/11859704681/job/33053273929
> chore(ci): swap out kc chainguard image to dockerhub image

- service/pkg/server/start.go
We run the server sdk in IPC mode so it does not reach out to well-known on instantiation because well-known isnt running yet. This means the token endpoint is never set. So if a service using the server sdk wanted to do a decrypt for example (a request that needs an auth token) they would get an error. 
This will manually set the token endpoint on instantiation using the issuer provided in the yaml config.
> fix(core): Set token endpoint manually if client creds provided in server sdk_config

- sdk/schema/manifest.schema.json
* mimetype is not required by the spec, dont require it in the manifest schema
> fix(sdk): Dont require mimetype in manifest schema

- service/authorization/authorization.go
- service/authorization/authorization_test.go
* Handle pagination limit/offset in `authorization.GetEntitlements`
* If quantity of attributes or subject mappings exceeds default "list" API limit as configured, we need to retrieve all to make accurate entitlement decision
> fix(authz): handle pagination in authz service

- service/health/health.go
- test/service-start.bats
Missed this while migrating to connect-rpc but accidentally removed the REST based healthcheck which causes kubernetes deployments to break.
> fix(core): expose rest based healthcheck

- service/internal/auth/casbin.go
- Always add 'unknown' casbin role, not just to users who have no roles
- Fixes bug where users with some realm roles, but not known ones, would not be able to rewrap
> fix(core): Allow more users to rewrap

- opentdf-dev.yaml
- opentdf-ers-mode.yaml
- opentdf-example.yaml
- service/internal/server/server.go
- test/service-start.bats
Fixes the grpc-gateway middleware chaining order. Handling of a cors pre-flight call before moving onto auth middleware.
> fix(core): properly chain grpc-gateway middleware order

- docker-compose.yaml
The keycloakdb service has been removed from the docker-compose file as it was not necessary for the current setup. This change helps streamline the configuration and prevents unnecessary resource allocation
* Keycloak runs in dev mode, no need for Postgres
> chore: Remove unused keycloakdb service from docker-compose

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
- service/pkg/auth/context_auth.go
- service/pkg/auth/context_auth_test.go
* enable setting context info and retrieving token/jwk from context from additional services added on platform extension
> feat(core): Expose context authn methods

- protocol/go/go.sum
- sdk/go.mod
- sdk/go.sum
- service/go.mod
- service/go.sum
> fix(core): Update fixtures and flattening in sdk and service

- examples/cmd/benchmark_decision.go
- go.work.sum
- service/authorization/authorization.go
* `GetEntitlements` is an expensive call. `GetDecisions` is calling `GetEntitlements` repetitively, despite no change in entities, but different Resource Attribute Policies. This can cause an unnecessary heavy load on the IDaP when a bulk amount Decisions are being made on one entity chain. 
* By getting all pertinent FAQs from the per Decision, and calling `GetEntitlements` per Decision will reduce IDaP load and have a huge performance win.
Compare the newly added benchmark test `benchmark-decision` result in commit `c9215db` before the benchmark test was made to the `HEAD` of this PR (`e903758`)
Follow the Platform Quickstart, and run `go run ./examples benchmark-decision --insecurePlaintextConn` for a quick test.
Locally, on PR changes
```
Benchmark Results:
Result: DECISION_PERMIT …
```
> fix(core): reduces GetEntitlements calls in GetDecisions

- service/authorization/authorization.go
- service/authorization/authorization_test.go
* if a resouce attribute fqn list only has "", DENY
* if a resource attribute fqn list has "" and other attributes, ignore the ""
* if a resource attribute fqn list has a non existent attribute, DENY
> fix(core): GetDecisions should handle empty string and non-existent attributes

- test/start-up-with-containers/action.yaml
* Doing things this way causes tests to fail due to specific keys being required
> chore(ci): we should update the entire list of keys rather than contanate them

- service/authorization/authorization.go
- service/authorization/authorization_test.go
* the length of the decision response array should be len(RAs) * len(ECs)
* add tests to catch future errors
> fix(core): Correct length of GetDecision response array

- service/authorization/authorization.go
- service/authorization/authorization_test.go
* deny for entity chain with no entities
* permit for resource attribute with no fqns
> fix(core): Return deny decision for empty entity chains

- .github/workflows/git-town.yaml
The 'autobump' PRs currently don't have a description, so they fail the git-town/action.
Sample Failure: https://github.com/opentdf/platform/pull/1849
This updates past git-town/action 1.0.7, which fixes an NPE when the PR description is empty
*
> chore(ci): Fix git-town on empty PR bodies

- sdk/auth/oauth/oauth.go
In Platform SDK, there is a corner case which is not handled by current logic which checks token expiration date. Currently, platform SDK uses monotonic clock for checking token expiration, but this clock is not running while PC sleeps/hibernates, thus causing wrong calculations of token expiration date and leading to sending of expired token to DSP.
From Go documentation (https://pkg.go.dev/time):
> **On some systems the monotonic clock will stop if the computer goes to sleep.** On such a system, t.Sub(u) may not accurately reflect the actual time that passed between t and u. The same applies to other functions and methods that subtract times, such as [Since](https://pkg.go.dev/time#Since), [Until](https://pkg.go.dev/time#Until), [Before], [After](https://pkg.go.dev/time#After), [Add], …
> fix(sdk): Fixed token expiration time

- examples/cmd/benchmark_decision.go
- service/authorization/authorization.go
* getDecisions calls `GetAttributeValuesByFqns` per `ResourceAttribute`, with bulk rewrap incoming, this can be quite expensive.
* rather than `GetAttributesValuesByFqns` per `ResourceAttribute` get all FQNs in one call by collecting them in the `ResourceAttribute`.
`go run ./examples benchmark-decision --insecurePlaintextConn  --count 1000`
locally I got 1.3s vs 80ms, so a very important performance change.
> fix(core): reduces GetAttributeValuesByFqns calls in getDecisions

- sdk/tdf.go
Previously we handled TDFs with missing split IDs as if each key split with no split ID should be
part of a different split. This was incompatible with the way that FileWatcher created TDFs; multiple
KAOs with no split IDs are part of a single split.
This removes this special-casing that groups splits with no IDs separately.
Tests for this case are [in a new xtest](https://github.com/opentdf/tests/pull/240)
> fix(sdk): everything is `mixedSplits` now

- sdk/schema/manifest-lax.schema.json
- sdk/schema/manifest.schema.json
- sdk/sdk.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_test.go
* Some users were gating on IsValidTDF, this makes that check an option for LoadTDF
Example usage:
```typescript
var s sdk.SDK
reader, err := s.LoadTDF(cipherText, s.WithSchemaValidation(sdk.Lax))
```
> feat(sdk): Allow schema validation during TDF decrypt

- sdk/kas_client.go
- sdk/nanotdf.go
- sdk/tdf.go
* Removes some casts of io.Read responses of `int` to the less accurate `uint32`.
> fix(sdk): Removes unnecessary down-cast of `int`

- CODEOWNERS
This changes CODEOWNERS to fix the `go.mod` definition to handle the fact that go.mod exists within subdirectories.
In addition `@opentdf/security` is being added as possible reviewers for these files so they we can help assist with safe dependency updates.  For example:
* https://github.com/opentdf/platform/pull/1852
* https://github.com/opentdf/platform/security/dependabot/31
* https://github.com/opentdf/platform/security/dependabot/32
* https://github.com/opentdf/platform/security/dependabot/29
* https://github.com/opentdf/platform/security/dependabot/36
* https://github.com/opentdf/platform/security/dependabot/35
* https://github.com/opentdf/platform/security/dependabot/34
* https://github.com/opentdf/platform/security/dependabot/33
N/A
> chore: Add security for reviewing dependency updates

- CODEOWNERS
This adds the security team to CODEOWNERS to `docs/go.*` so that we can assist with dependency updates.  This was missed as a go directory in PR #1878, discovered through the update needed in PR https://github.com/opentdf/platform/pull/1882
N/A
> chore: Add security to CODEOWNERS for docs/go.*

- .github/workflows/sonarcloud.yml
- .github/workflows/vulnerability-check.yaml
This should fix the failing vulncheck
*
> chore(ci): updates ci to go 1.22.11

- service/kas/access/rewrap.go
- return 500s if keygen fails
- simplify debug logging of legacy (non-bulk) rewrap requests
> fix(core): improve logging and errors on rewrap

- sdk/tdf_test.go
- Validates a cast is `ok` in a test function for a known value
- Newer versions of golangci-lint will fail on this line with `errcheck`
> chore(sdk): Fixes future linter error

- service/internal/security/standard_crypto.go
- service/kas/access/provider.go
- service/kas/access/provider_test.go
- service/kas/access/publicKey.go
- service/kas/access/publicKey_test.go
- service/kas/kas.go
- test/tdf-roundtrips.bats
- When loading KAS keys, validate that key identifiers are unique
- This will be required as we move to a key ID - first (instead of alg first) method of selecting keys
- While here, moved some of the 'legacy conversion' code into more testable functions and generally improved testing and handling/detection of error conditions, including increasing test coverage of loading/displaying EC keys
> fix(core): Requires unique kids

- sdk/auth/oauth/oauth.go
- sdk/auth/oauth/oauth_test.go
- sdk/auth/token_adding_interceptor.go
- sdk/httputil/http.go
- sdk/options.go
- sdk/sdk.go
This change switches us from maintaining a tls config which we then on-demand initialize an `http.Client` with to instead maintain and reuse an `http.Client` instance. This enables us to utilize the connection pooling which occurs within the `http.Transport` to reduce ssl handshakes and thus reduce latency.
In addition this change provides us a central place to configure out `http.Client` (`httputil`). Allowing us to easily set configuration options to reduce the security risks of using an unconfigured `http.Client`. Notably timeouts to reduce DoS risks, and control around following redirects to prevent blind SSRF's.
This PR 3/4 addresses #1891.  After it's merged a small change will be made in the `service` to fully utilize the API being introduced in the SDK here.
> fix: Improve http.Client usage for security and performance

- service/kas/access/keyaccess.go
- service/kas/access/rewrap.go
* Javascript still uses the old, non-bulk request object format for rewrap
* As such, the logic for upgrading the request body needs to support the ec wrapped kao type
> fix(core): Fixes for ec-wrapped from js client

- .github/workflows/traffic.yaml
* the labels on the metrics we are pulling for the repos need to be updated, they are still the names of the old repos. this is making reporting confusing. this pr updates the labels to match the repos they are reporting about. 
* you can trigger this workflow manually and view the json output to have the correct labels.
> chore(main): update labels for repo metrics

- .github/workflows/release.yaml
* This shouldn't matter, since go package names cannot contain spaces, but this fixes an issue where spaces in the release paths would cause the for loop to fail.
> chore(ci): actionlint fix

- sdk/options.go
- sdk/sdk.go
- sdk/sdk_test.go
* Validates healthy platform is available within `sdk.New` when triggered
* Provides precise error if error connecting to provided `platformEndpoint` or status is unhealthy
* Exposes validation function from SDK module for DX
Resolves https://github.com/opentdf/platform/issues/1935
> feat(sdk): sdk.New should validate platform connectivity and provide precise error

- .github/workflows/release.yaml
- This is already escaped (as evidenced by the existing calls to fromJSON elsewhere)
- from [the doc](https://github.com/googleapis/release-please-action?tab=readme-ov-file#outputs):
> `paths_released`: A JSON string of the array of paths that had releases created ([] if )
*
> chore(ci): Fixes release path double-escaping

- sdk/auth/token_adding_interceptor.go
- sdk/auth/token_adding_interceptor_test.go
- service/internal/auth/authn_test.go
- service/pkg/server/start.go
This PR follows #1910 by updating `service` to utilize the new `httputil` helper for constructing a client which wont follow redirects, and has sensible timeouts. To quote that description:
> This change switches us from maintaining a tls config which we then on-demand initialize an http.Client with to instead maintain and reuse an http.Client instance. This enables us to utilize the connection pooling which occurs within the http.Transport to reduce ssl handshakes and thus reduce latency.
>
> In addition this change provides us a central place to configure out http.Client (httputil). Allowing us to easily set configuration options to reduce the security risks of using an unconfigured http.Client. Notably timeouts to reduce DoS risks, and control around following redirects to prevent …
> fix: Service utilize `httputil.SafeHttpClient`

- service/kas/access/rewrap.go
* Fixes some code in bulk rewrap that wasn't properly assigning the errors - or returning the correct error code - to the 'response' objects. 
* This most notably was causing failures with mixed EC and RSA wrapping requests, and for some 400s to be 500s.
> fix(core): Fixes merge fail in bulk logic

- sdk/sdk.go
- sdk/sdk_test.go
* Also rely more on parsing using `net` and `url` libraries as opposed to regex
> fix: Allow parsing IPs as hostnames

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/auth/config.go
- service/pkg/server/options.go
This pull request introduces changes to add IPC reauthorization routes and improve the testing of the authentication service. The most important changes include adding new routes for IPC reauthorization, modifying the `Authentication` struct and its methods, and updating the test suite to include tests for the new functionality.
*
> fix(main): add ipc auth extensibility

- sdk/tdf.go
- sdk/tdf_config.go
- This was dropped during merging in the support for EC session keys
> fix(sdk): Allow reuse of session key

- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- Lets IPC middleware share DPoP htu resolution logic with the existing middleware
- This fixes an issue where the htu fail when set to the gateway path (like /v2/rewrap) but the IPC only expects the new connect path (the name of the rpc procedure)
> fix(core): Fix DPoP with grpc-gateway

- sdk/tdf.go
* Previously, the error was always "could not find policy in rewrap response" even if error was that it couldnt connect to the provided kas url. With this change it will properly return the error from the kas request if one is present.
> fix(sdk): Display proper error on kas rewrap failure

- .github/scripts/init-temp-keys.cmd
- .github/scripts/init-temp-keys.sh
- .github/workflows/checks.yaml
* fixes issue with pull errors from chainguard
> fix(ci): Use dockerhub keycloak image in init-temp-keys scripts

- service/go.mod
`go mod tidy` was not run after migrating the mapstructure dependency to use the viper fork
> fix(core): fix service go.mod

- .github/dependabot.yml
- differing `allow` blocks is insufficient differentiation
- see: https://github.com/opentdf/platform/runs/41658077888
> chore(ci): Fix duplicate dependabot stanzas

- service/integration/subject_mappings_test.go
- service/policy/db/query.sql
- service/policy/db/query.sql.go
* populates mapped attribute value FQNs on matched subject mappings
> feat(policy): GetMatchedSubjectMappings should provide value FQN

- service/README.md
- service/pkg/server/options.go
* Fix interface changes, relating to https://github.com/opentdf/platform/pull/1715
> chore(docs): small improvements about registration

- .github/workflows/pr-checks.yaml
- lib/fixtures/keycloak.go
- lib/ocrypto/ec_key_pair.go
> fix: perfsprint lint issues

- .github/labeler.yml
- .github/workflows/label.yaml
Adding label workflow which has one job at this time  and that is to label pull requests with `external-contributor` if  the user opening the pull request is not a member of the org. 
This workflow keys off of `author_associations` from the pull request context.  
Best [link](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) that I could find to describe each association 
Also adds the following actions
- https://github.com/CodelyTV/pr-size-labeler
- https://github.com/actions/labeler
> chore(ci): add label workflow

- .github/workflows/checks.yaml
- Makefile
- examples/cmd/attributes.go
- examples/cmd/authorization.go
- examples/cmd/benchmark.go
- examples/cmd/benchmark_bulk.go
- examples/cmd/benchmark_decision.go
- examples/cmd/decrypt.go
- examples/cmd/docs.go
- examples/cmd/encrypt.go
- examples/cmd/examples.go
- examples/cmd/isvalid.go
- examples/cmd/isvalid_test.go
- examples/cmd/kas.go
- examples/cmd/metrics.go
- service/entityresolution/claims/entity_resolution.go
- service/entityresolution/keycloak/entity_resolution.go
* Some fixes for example code in the linter / formatter
* Suppresses a lot of revive (unnecessary or dangerous renames) and things like nestif (unneeded refactor of code only lightly covered by tests) and forbidigo (yeah, sample code often uses Println, why make such a big deal over it)
* Get rid of 'only changes', as we are now 100% green. We can add it back whenever we upgrade/change lint settings as needed
* Fix makefile so links are clickable in vscode again
> chore(examples): Lint fixes

- service/internal/security/crypto_provider.go
- service/internal/security/in_process_provider.go
- service/internal/security/standard_crypto.go
- service/internal/security/standard_only.go
- service/internal/server/server.go
- service/kas/access/provider.go
- service/kas/access/publicKey.go
- service/kas/access/publicKey_test.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
- service/kas/kas.go
- test/tdf-roundtrips.bats
- The code path for KAOs that do not contain key identifier strings did not use the new trust.KeyIndex plugin, if one is provided
- Now the code will prefer to use the index, if it is available and the 'keyring' config is not set
- Also fixes an issue where defaulting to 'standard' in the config caused the 'in memory' crypto config (standard) to always be used, as `IsEmpty` would always return true
> fix(core): Let legacy KAOs use new trust plugins

- service/internal/subjectmappingbuiltin/subject_mapping_builtin_actions.go
- service/internal/subjectmappingbuiltin/subject_mapping_builtin_actions_test.go
* enhance `subjectmappingplugin` with actions in response to subject mapping evaluation
> feat(authz): subject mapping plugin support for ABAC with actions

- .github/dependabot.yml
* These will have to be added back to each separate go.mod if we want them, since the current dependabot.yaml is failing with the message:
> Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'. Ecosystem 'gomod' has overlapping directories.
> chore(ci): Stops dependabot for 3rd party go mods

- service/policy/db/key_access_server_registry.go
- service/policy/db/utils.go
- service/policy/db/utils_test.go
> fix: handle empty private and public key ctx structs

- sdk/sdk.go
* connection options should be passed to `getPlatformConfiguration`.
> fix(sdk): adds connection options to getPlatformConfiguration

- docs/Configuring.md
- opentdf-dev.yaml
- opentdf-example.yaml
- service/pkg/db/db.go
- service/pkg/db/db_test.go
* Expose connection/pooling configuration settings to global config settings
> feat(core): enhance db configuration options

- service/integration/attribute_values_test.go
- service/integration/attributes_test.go
- service/integration/namespaces_test.go
- service/internal/fixtures/policy_fixtures.yaml
- service/policy/db/attribute_values.go
- service/policy/db/attributes.go
- service/policy/db/key_access_server_registry.go
- service/policy/db/namespaces.go
1.) Ensure non-active keys cannot be assigned.
> fix(policy): Ensure non active keys cannot be assigned.

- .github/workflows/action-lint.yaml
- .github/workflows/checks.yaml
- .github/workflows/codeql.yaml
- .github/workflows/friendly-reminders.yaml
- .github/workflows/label.yaml
- .github/workflows/languagetool.yaml
- .github/workflows/nightly-build.yaml
- .github/workflows/nightly-checks.yaml
- .github/workflows/pr-checks.yaml
- .github/workflows/release-build.yaml
- .github/workflows/release.yaml
- .github/workflows/sonarcloud.yml
- .github/workflows/stale.yaml
- .github/workflows/traffic.yaml
- .github/workflows/vulnerability-check.yaml
- test/start-additional-kas/action.yaml
- test/start-up-with-containers/action.yaml
* I saw that the `bats` setup action wasn't pinned, so pinned that
* and it annoyed me it wasn't easy to see what the versions of the other pins were
> chore(ci): Annotate pinned actions with versions

- service/policy/actions/actions.go
- service/policy/attributes/attributes.go
- service/policy/kasregistry/key_access_server_registry.go
- service/policy/keymanagement/key_management.go
- service/policy/namespaces/namespaces.go
- service/policy/registeredresources/registered_resources.go
- service/policy/resourcemapping/resource_mapping.go
- service/policy/subjectmapping/subject_mapping.go
- service/policy/unsafe/unsafe.go
* Each policy service should gracefully close its db client connections on shutdown
> fix(policy): all policy services should gracefully close

- service/policy/db/subject_mappings.go
> fix(policy): remove support for creation/updation of SubjectMappings with deprecated proto actions

- sdk/tdf.go
- sdk/tdf_test.go
* Adds Seeking to SDK so write can have offset when using `WriteTo`. This is useful when the TDF is large but only want a specific segment from the data. 
* Also `ReadAt` had an off by one error decrypting one extra segment when it was not required to do so.
> feat(sdk): adds seeker interface to TDF Reader

- service/integration/keymanagement_test.go
- service/policy/db/migrations/20250605000000_unique_provider_name.md
- service/policy/db/migrations/20250605000000_unique_provider_name.sql
- service/policy/db/schema_erd.md
1.) Make the **provider_name** for the provider configuration unique.
> feat(policy): Unique name for the key provider.

- service/entityresolution/keycloak/entity_resolution.go
- service/entityresolution/keycloak/entity_resolution_test.go
- service/entityresolution/keycloak/v2/entity_resolution.go
- service/entityresolution/keycloak/v2/entity_resolution_test.go
> fix: only request a token when near expiration

- docs/Configuring.md
- service/cmd/keycloak_data.yaml
> feat(core): DSPX-609 - add cli-client to keycloak provisioning

- service/integration/kas_registry_key_test.go
- service/integration/keymanagement_test.go
- service/policy/db/key_access_server_registry.go
- service/policy/db/migrations/20250609000000_restrict_provider_deletion.md
- service/policy/db/migrations/20250609000000_restrict_provider_deletion.sql
- service/policy/db/schema_erd.md
1.) Update **key_access_server_keys** table to not allow deletion of in-use provider configurations
2.) Remove application level check for provider_configuration, in-favor or db level
> feat(policy): Restrict deletion of pc with used key.

- examples/cmd/benchmark_decision.go
- examples/cmd/benchmark_decision_v2.go
- service/cmd/keycloak_data.yaml
> fix(core): replace opentdf-public client with cli-client

- service/authorization/authorization.go
- service/logger/contextHandler.go
- service/logger/logger.go
- service/pkg/db/errors.go
- service/pkg/server/services.go
- service/policy/actions/actions.go
- service/policy/attributes/attributes.go
- service/policy/db/namespaces.go
- service/policy/db/registered_resources.go
- service/policy/kasregistry/key_access_server_registry.go
- service/policy/keymanagement/key_management.go
- service/policy/namespaces/namespaces.go
- service/policy/registeredresources/registered_resources.go
- service/policy/resourcemapping/resource_mapping.go
- service/policy/subjectmapping/subject_mapping.go
- service/policy/unsafe/unsafe.go
* Pulls context values into logs that are set to contexts within RPC requests by our interceptors
* Improves correlation by better propagating request IDs throughout all logs within the RPC handlers
* Updates `db.StatusifyError` to take in context and a service logger so error logs are correlated with services and contextualized requests
```shell
time=2025-06-13T14:01:04.501-07:00 level=DEBUG msg="creating new attribute definition" namespace=policy name=testing5 request-id=771749b3-a1fb-488e-9710-b94c30cf3d5d user-agent="connect-go/1.18.1 (go1.24.2)" request-ip=None actor-id=80ff2bda-e446-4b3c-8197-ba980540d293
```
> feat(core): consume RPC interceptor request context metadata in logging

- sdk/assertion.go
- sdk/tdf_test.go
> fix: set consistent system metadata id and schema

- docs/Configuring.md
- service/internal/server/server.go
- service/pkg/cache/cache.go
- service/pkg/cache/cache_test.go
- service/pkg/cache/config.go
- service/pkg/cache/config_test.go
- service/pkg/cache/ristretto.go
- service/pkg/cache/ristretto_test.go
- service/pkg/server/services.go
- service/pkg/server/services_test.go
- service/pkg/server/start.go
- service/pkg/server/start_test.go
- service/pkg/serviceregistry/serviceregistry.go
- service/pkg/util/relativesizes.go
- service/pkg/util/relativesizes_test.go
* Add cache manager which allows services to implement cache while offering platform governance
> feat(core): add cache manager

- service/internal/server/server.go
- service/pkg/cache/cache.go
- service/pkg/cache/cache_test.go
- service/pkg/server/services.go
- service/pkg/server/start.go
- service/pkg/server/start_test.go
- service/pkg/serviceregistry/serviceregistry.go
* Current implementation allows one type per cache client
* Cannot genericize `cache.Set` easily as Go does not support method generics
* Allows consumers to get/set `any` type and do their own assertion on retrieved cache hits
> fix(core): remove generics on new platform cache manager and client

- service/pkg/cache/cache.go
- service/pkg/cache/cache_test.go
- service/pkg/server/start.go
Add cleanup for underlying Ristretto cache by tracking and explicitly closing it to avoid goroutine leaks and ensure proper resource release.
Details:
Modified cache.Manager to store a reference to the underlying *ristretto.Cache.
Added a Close() method to Manager that calls .Close() on the underlying Ristretto cache.
Why:
Ristretto starts background goroutines and allocates internal buffers that aren't automatically cleaned up. Explicitly calling .Close() ensures proper shutdown, especially important in tests and long-running services
> feat(main): Add Close() method to cache manager

- service/integration/registered_resources_test.go
- service/policy/db/query.sql
- service/policy/db/query.sql.go
> feat(policy): allow ListRegisteredResources to return ActionAttributeValues on RegisteredResourceValues

- service/entityresolution/keycloak/v2/entity_resolution.go
- service/entityresolution/keycloak/v2/entity_resolution_test.go
- service/entityresolution/keycloak/v2/retrieve.go
- service/entityresolution/keycloak/v2/retrieve_test.go
- service/pkg/cache/cache.go
- Centralizes Keycloak entity retrieval logic into helper functions (retrieve.go)
- Adds caching for Keycloak lookups (clients, users, groups, group members)
- Updates entity resolution code to use cached helpers
- Improves performance by reducing redundant Keycloak requests
- No API changes; internal refactor only
- Adds tests for cache integration and expiration
> feat(authz): Add caching to keycloak ERS

- opentdf-dev.yaml
- service/internal/server/server.go
* ability to specify read, write, readheader, and idle timeouts and maxheaderbytes via the opentdf.yaml
> feat(core): Add the ability to configure the http server settings

- examples/cmd/encrypt.go
- sdk/basekey.go
- sdk/basekey_test.go
- sdk/granter.go
- sdk/granter_test.go
- sdk/kas_client.go
- sdk/tdf.go
- sdk/tdf_config.go
- sdk/tdf_test.go
- service/internal/security/crypto_provider.go
- service/internal/security/standard_crypto.go
- service/trust/delegating_key_service.go
- test/start-up-with-containers/action.yaml
When key mappings (grants now with key ids!) are available,
prefer those values when possible, even if that means having multiple
mechanism types in the same TDF (e.g. RSA keys of different lengths).
This was always the intent, but apparently didn't work before.
I've added a couple of small tests,
and now will add more to the integration tests.
Also, updates `start-up-with-containers` to automatically drop unsupported key types on older kases.
This will simplify xtest loading the newly supported key types.
* the `kao template` type is now the preferred input format for `prepareManifest`
* move migration code (from `splitPlan`) into separate method
* modifies tests to correctly associate keys with key ids
> fix(sdk): Prefer KID and Algorithm selection from key maps

- lib/ocrypto/ec_key_pair.go
- service/internal/security/basic_manager.go
- service/internal/security/basic_manager_test.go
- service/internal/security/in_process_provider.go
- service/kas/access/publicKey_test.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
- service/kas/key_indexer.go
- service/kas/key_indexer_test.go
- service/trust/delegating_key_service_test.go
- service/trust/key_index.go
1.) Return standardized algorithm formatted string from default key indexer.
> refactor(policy): Return standardized algorithm string from indexer.

- service/internal/security/in_process_provider.go
- service/kas/access/publicKey_test.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
- service/kas/key_indexer.go
- service/kas/key_indexer_test.go
- service/trust/delegating_key_service.go
- service/trust/delegating_key_service_test.go
- service/trust/key_index.go
1.) Create a new function for **key_index** called ListKeysWith allowing developers to pass in common ListKeyOptions
2.) Modify ListKeys/FindKeyByAlgorithm within **key_indexer** to support listing legacy keys.
> feat(policy): Modify KAS indexer to support legacy keys.

- .github/workflows/checks.yaml
- For buf breaking, the base should be the pull request target, on pull requests
- For go mod replace directive checks, check all release please branches, not just main ones
> chore(ci): Fixes for checks for buf and go mods

- .github/workflows/main-dependency-review.yaml
The `base-ref` for dependency review is typically the target branch you're merging into. This results in dependency-review alerting on any changed dependencies which may have CVE's. By using `orign/main` as our `base-ref`, we are now also validating that the target branch has adopted all necessary security updates that were adopted within the `main` branch. This will help ensure `release` branches have adopted all necessary security fixes.
> chore: Add dependency-review workflow that always targets `main`

- lib/ocrypto/ec_key_pair.go
- lib/ocrypto/interfaces.go
- lib/ocrypto/protected_key.go
- lib/ocrypto/protected_key_test.go
- service/internal/security/basic_manager.go
- service/internal/security/in_process_provider.go
- service/kas/access/rewrap.go
- service/trust/delegating_key_service_test.go
- service/trust/key_manager.go
- Prefer using the Encapsulate interface method, when possible
- Deprecate the Key's Export method, since we generally don't want to export the keys and Encapsulate is more accurate for what we want.
- The goal here is to present an interface that supports a fully delegated rewrap, e.g. using a [Luna Functionality Module](https://thalesdocs.com/gphsm/luna/7/docs/network/Content/FM_SDK/preface.htm) or other KAS. In this case, the call to Encapsulate would trigger the external rewrap.
> feat(core): Encapsulate>Encrypt

- service/pkg/server/options.go
- service/pkg/server/services.go
- service/pkg/server/services_test.go
- service/pkg/server/start.go
- service/pkg/server/start_test.go
- service/pkg/serviceregistry/serviceregistry.go
- service/trust/delegating_key_service.go
- service/trust/key_manager.go
- Some of our newer KMS implementations do some health checks and other things during their init phase.
- This was always intended as an option for the init, so we always should have allowed passing in a context
- I made this an explicit parameter to satisfy the golang linter that prevents context from being a parameter (in `KeyManagerFactoryOptions`
- This means we need to have new types for a lot of things
- and to avoid breaking changes while downstream service implementations pick this up, this implements bidirectional compatibility, upgrading factories that don't take context to ignore it, and downgrading services that don't set it to use `Background` context
> feat(core): Lets key manager factory take context

- service/pkg/server/services.go
- service/pkg/server/services_test.go
- service/pkg/serviceregistry/serviceregistry.go
So right now I have inter-PEP dependencies, so config/PEP-A for example. PEP-A wants to set its config to the config service, for later viewing/editing in another interface. Currently the only place available for this is PEP-A's Init (RegisterFunc). So, right now, this is the solution I'm using. I think there is an alternative with some "OnServicesStarted" type hook or something as well (which might be more useful maybe).
> fix(core): return services in the order they were registered

- docs/Configuring.md
- opentdf-dev.yaml
- opentdf-ers-mode.yaml
- opentdf-example.yaml
- opentdf-kas-mode.yaml
- service/internal/auth/authn.go
- service/internal/auth/authn_test.go
- service/internal/auth/config.go
- service/pkg/auth/context_auth.go
- service/pkg/auth/context_auth_test.go
- adds config for a client ID claim in OIDC access tokens (dot notation capable)
- utility functions to set and get the client ID from golang context metadata (which is made available across gRPC service boundaries, unlike golang context keys that are _not_ saved to the context metadata)
- reads config into various interceptors
- each interceptor propagates the clientID from the parsed token for downstream consumers
- improvements to logs alongside `azp` claim
- unit and integration tests
> feat(core): propagate token clientID on configured claim via interceptor into shared context metadata

- docs/Configuring.md
* at some point we renamed `preview_features` to `preview`
> chore(docs): Fix unrenamed field in docs

- service/kas/access/accessPdp.go
- service/kas/access/rewrap.go
- service/kas/access/rewrap_test.go
1.) Add logic to retrieve obligations from request header during rewrap
2.) Add logic to populate required obligations on kas response object
Smoke tests tried manually (no key split or bulk rewrap):
- Obligations are not fulfilled, rewrap fails
- Obligations are fulfilled, rewrap succeeds
> feat(policy): Add obligation support to KAS

- .github/workflows/checks.yaml
- opentdf-dev.yaml
- service/internal/server/server.go
- test/service-cors.bats
Implemented bats tests to verify CORS configuration, ensuring proper handling of preflight requests, allowed headers (e.g., Authorization, Content-Type, Connect-Protocol-Version), and wildcard origin support. Validated response headers like Access-Control-Allow-Origin and credentials allowance.
See test failure: https://github.com/opentdf/platform/actions/runs/18286756662/job/52063687108?pr=2787
> fix(core): CORS
