opentdf/platform

examples/cmd/encrypt.go
Use `--platformEndpoint` in encrypt example
=> fix(examples): platformEndpoint

README.md
=> docs: README heading

.github/workflows/checks.yaml, .github/workflows/lint-all.yaml, .gitignore, Dockerfile, Makefile, README.md, examples/go.mod, examples/go.sum, go.work, go.work.sum, sdk/go.mod, sdk/go.sum, service/go.mod, service/go.sum
- Don't build them
- Removes replace directives as well
=> chore: Checks in go.work and sum again

.github/workflows/checks.yaml, .github/workflows/vulnerability-check.yaml, examples/go.mod, go.work, go.work.sum, lib/ocrypto/go.mod, protocol/go/go.mod, sdk/go.mod, sdk/go.sum, service/go.mod
Also explicitly updates net library to fix vulnerability in http2
=> chore: Updates to golang 1.21.9

examples/cmd/decrypt.go, service/authorization/authorization_test.go, service/cmd/migrate.go, service/cmd/policy.go, service/cmd/provisionFixtures.go, service/integration/main_test.go, service/integration/namespaces_test.go, service/policy/db/attributes.go
These were exclusively fmt.Print calls
=> chore(lint): Fix all forbidigo errors

.github/workflows/nightly-build.yaml, Dockerfile
Adds nightly container build to start building the platform. Also signs it with cosign.
=> ci: nightly container build

.release-please-manifest.json, release-please.json
- One v0 versions, bump the minor for breaking changes (`bump-minor-pre-major`). This should prevent it from release 1.x as our first release
- Remove redundant lines
- Fixes for manifest
=> chore(cd): release-please fixes

.github/workflows/sonarcloud.yml, sonar-project.properties
=> chore(main): Enable SonarCloud analysis with collecting code coverage values

docs/configuration.md, opentdf-dev.yaml, opentdf-example-no-kas.yaml, opentdf-example.yaml, opentdf-with-hsm.yaml, service/internal/auth/config.go
Closes https://github.com/opentdf/platform/issues/696
=> fix(config): update docs for enforce dpop config and clean up markdown tables

README.md
Resolves https://github.com/opentdf/platform/issues/736
=> fix(docs): broken link and spelling

.github/workflows/checks.yaml, .github/workflows/lint-all.yaml, .github/workflows/sonarcloud.yml, examples/go.mod, go.work, lib/fixtures/go.mod, lib/ocrypto/go.mod, protocol/go/go.mod, sdk/go.mod, service/go.mod
Fixes for vuln https://pkg.go.dev/vuln/GO-2024-2824
=> chore(core): Updates go patch version

service/cmd/provisionFixtures.go
addresses https://github.com/opentdf/platform/issues/786
=> fix(ci): Use the correct schema with the provision fixture command

service/pkg/serviceregistry/serviceregistry.go
Annotate serviceregistry to setup for future documentation enhancements
=> feat(docs): improve serviceregistry doc annotations

lib/fixtures/keycloak.go, sdk/auth/token_adding_interceptor.go, service/entityresolution/keycloak/keycloak_entity_resolution.go, service/internal/auth/authn.go
Fixes unbalanced/unknown key issues in slog
=> fix(core): Updates logs statements to log errors

go.work.sum, service/cmd/policy.go
=> fix(policy): fix policy fqn-reindex command schema suffix

examples/cmd/encrypt.go, sdk/nanotdf.go, service/kas/access/rewrap.go
=> feat(kas): Add access check for nano rewrap

service/policy/db/attributes.go
=> fix(policy): downgrade policy SQL statement info level logs to debug

opentdf-dev.yaml, opentdf-example.yaml, service/internal/security/standard_crypto.go
=> fix(kas): lowercase config mapstructure for kas key paths

go.work.sum, sdk/go.mod, sdk/go.sum, sdk/options.go, sdk/platformconfig.go, sdk/sdk.go, sdk/sdk_test.go, sdk/tdf_test.go, service/rttests/rt_test.go
This pr leverages the platform wellknown endpoint to drive sdk configuration. For example discovering the appropriate idp token endpoint for the platform.
=> feat(sdk): leverage platform wellknown configuration endpoint

service/internal/server/server.go
Resolves https://github.com/opentdf/platform/issues/898
=> fix(kas): misleading hsm error message

examples/cmd/encrypt.go, lib/ocrypto/ec_key_pair.go, lib/ocrypto/ec_key_pair_test.go, sdk/nanotdf.go, sdk/nanotdf_config.go, service/internal/security/crypto_provider.go, service/internal/security/hsm.go, service/internal/security/standard_crypto.go, service/kas/access/rewrap.go
- Adds `VerifyPolicyBinding` method to SDK
- Moves relevant shared code to `ocrytpo`
=> feat(sdk): Support for ECDSA policy binding on both KAS and SDK

opentdf-dev.yaml, opentdf-example-no-kas.yaml, opentdf-example.yaml, opentdf-with-hsm.yaml
Resolves https://github.com/opentdf/platform/issues/924
=> fix(core): example configs should specify cors.allowedorigins as []string

.github/workflows/checks.yaml, test/service-start.bats
Using the bats tool will allow easier local testing and improve readability of test results and test content
=> chore(ci): Migrate tests to bats

service/go.mod, service/internal/auth/authn.go, service/internal/auth/authn_test.go, service/internal/logger/audit/logger.go, service/internal/logger/logger.go, service/internal/server/server.go, service/pkg/server/start.go, service/pkg/server/start_test.go
This adds a new log level of `TRACE` that we can take advantage of for logs that we might find noisy on debug but might need to capture during a triaging scenerio. 
Resolves:
- #968 
- #970
=> feat: adds new trace log level

service/go.mod, service/go.sum, service/internal/subjectmappingbuiltin/subject_mapping_builtin.go, service/internal/subjectmappingbuiltin/subject_mapping_builtin_test.go
resolves https://github.com/opentdf/platform/issues/645
=> feat(authz): Use flattened entity representations in subject mapping evaluation

service/internal/logger/audit/getDecision_test.go, service/internal/logger/audit/helpers_test.go, service/internal/logger/audit/logger.go, service/internal/logger/audit/logger_test.go, service/internal/logger/audit/policy_test.go, service/internal/logger/audit/rewrap_test.go, service/internal/logger/audit/utils.go, service/internal/logger/audit/utils_test.go, service/internal/logger/logger.go
=> chore: Audit Logging Tests

service/rttests/rt_test.go
This improves error output and makes it easier to use tools to run just the failing test
=> chore(ci): Update rt-test to use a suite

sdk/sdk.go
=> feat(sdk): support unsafe policy service in SDK

service/integration/attribute_values_test.go, service/integration/attributes_test.go, service/policy/db/attribute_values.go, service/policy/db/attributes.go
Closes https://github.com/opentdf/platform/issues/1102
=> fix(policy): ensure get requests of attributes and values contain any KAS grants

go.work.sum, opentdf-dev.yaml, opentdf-example.yaml, service/entityresolution/keycloak/keycloak_entity_resolution.go, service/entityresolution/keycloak/keycloak_entity_resolution_test.go
should resolve all
https://github.com/opentdf/platform/issues/1063
https://github.com/opentdf/platform/issues/1036
https://github.com/opentdf/platform/issues/1055
=> feat(authz): Keycloak ERS ability to handle clients, users, and emails that dont exist

service/entityresolution/keycloak/keycloak_entity_resolution.go, service/entityresolution/keycloak/keycloak_entity_resolution_test.go
Add tests for https://github.com/opentdf/platform/pull/1113
=> chore(authz): Add tests for Keycloak ERS entity not found handling

.github/workflows/checks.yaml, examples/README.md, examples/cmd/attributes.go, examples/cmd/authorization.go, examples/cmd/encrypt.go, examples/cmd/errors.go, examples/go.mod, test/policy-service.bats
- `example attribute ...`
- `ls [-N http://name.space]`: List all attributes and values, or all in the requested namespace
- `add -a https://name.space/attr/attrname -v "v1 v2 v3" [-r anyof]` Defines and attribute
- `rm -a https://a.b/attr/n [-v "just the values to remove"]`
=> feat(examples): adds attribute `ls,add,rm` cmds

.github/workflows/checks.yaml
need to merge opentdf/tests PR first
https://github.com/opentdf/tests/pull/153
=> feat(ci): Add xtest to ci workflow

service/internal/auth/casbin.go, service/internal/auth/casbin_test.go
Related to https://github.com/virtru-corp/data-security-platform/issues/474
=> fix(core): improve casbin ExtendDefaultPolicy and add test

service/authorization/authorization.go, service/authorization/authorization_test.go, service/entityresolution/keycloak/keycloak_entity_resolution.go, service/internal/entitlements/pdp.go, service/internal/subjectmappingbuiltin/subject_mapping_builtin.go, service/internal/subjectmappingbuiltin/subject_mapping_builtin_test.go, service/policies/entitlements/entitlements.rego, test/rego/custom-entity.rego, test/rego/static-entitlements.rego
resolves https://github.com/opentdf/platform/issues/1218
resolves https://github.com/opentdf/platform/issues/1217
=> feat(authz): Move ERS call out of rego and include all entities in requests

service/integration/subject_mappings_test.go
Related to https://github.com/opentdf/otdfctl/issues/244
=> fix(core): policy subject mapping integration test addition for 'contains' operator

sdk/internal/autoconfigure/granter.go, sdk/internal/autoconfigure/granter_test.go
These are allowed in DNS names
https://github.com/opentdf/platform/issues/1214
=> fix(sdk): Allow hyphens in attr namespaces

.github/workflows/checks.yaml, go.work.sum
resolves https://github.com/opentdf/platform/issues/1252
=> chore(ci): check for associated issue on pull request

.github/workflows/stale.yaml
=> fix(ci): fix stale issue detection workflow

service/kas/kas.proto
resolves https://github.com/opentdf/platform/issues/1286
=> chore(kas): Remove unimplemented `kas.info` rpc

service/buf.yaml
=> fix(core): put back proto breaking change detection in CI

service/internal/auth/casbin.go
resolves https://github.com/opentdf/platform/issues/1306
=> fix(core): Update casbin policy for rewrap with unknown role

service/logger/audit/constants.go, service/policy/namespaces/namespaces.go
Resolves #1332 (partially, not yet LIST)
=> feat(core): add RPCs to namespaces service to handle assignment/removal of KAS grants

.github/workflows/checks.yaml
- Fixes #1372 
- Explanation: https://github.com/bufbuild/buf-setup-action?tab=readme-ov-file#github-token
- Sample :snowflake: https://github.com/opentdf/platform/actions/runs/10424675065/job/28873938908#step:3:11
=> chore(ci): Address rate limit failures

docs/configuration.md
chore(docs): describe how environment variables work
Follow up work on deployment modes updating the configuration docs.
=> chore(docs): cleanup docs to describe new mode and sdk_config

sdk/platformconfig.go, sdk/sdk_test.go
=> fix(sdk): well-known warning logs and public client id error

service/policy/db/migrations/20240813000000_drop_attribute_value_members.sql
=> fix: migration missing conditional

sdk/kas_client.go
Resolves https://github.com/opentdf/platform/issues/1429
=> fix(sdk): set kas key cache ttl to 5 minutes

sdk/tdf.go
Resolves https://github.com/opentdf/platform/issues/1433
=> fix: update to allow for using handling assertiongs

service/integration/attribute_fqns_test.go, service/internal/access/pdp.go
=> fix(core): case sensitivity in AccessPDP

.github/workflows/checks.yaml, service/internal/auth/authn.go
=> fix: remove access token log even on failure

service/kas/access/rewrap.go
- Removes some stray unused, out of date code
- Probably should have been removed as part of #744 
- Fixes #1124
=> fix(core): Fix flake in nano rewrap

Makefile, README.md, service/policy/adr/0001-generate-policy-erd.md, service/policy/db/README.md, service/policy/db/schema_erd.md
Resolves #1518 
Resolves #1225
1. Adds ADR for generating the schema
2. Adds a makefile script to generate SQLC code and generate a new ERD (with tool checks)
3. updates various documentation
=> feat(policy): generate policy ERD

.github/workflows/checks.yaml, service/main.go, service/policy/policy.go
Relates to https://github.com/opentdf/otdfctl/issues/347
Resolves #1528
=> feat(ci): run otdfctl e2e tests within platform

sdk/granter.go, sdk/granter_test.go, sdk/tdf.go
resolves https://github.com/opentdf/platform/issues/1543
=> fix(sdk): Granter offline mode with namespaces and keycache

sdk/nanotdf.go, sdk/nanotdf_config.go, sdk/nanotdf_test.go
fixes https://github.com/opentdf/platform/issues/1548
=> fix(sdk): Fix nanotdf ECC mode bitfield

service/kas/access/geoTDF.go, service/kas/access/geoTDF_test.go, service/kas/access/provider.go, service/kas/access/rewrap.go
- Adds ability to load public keys in geotdf config for signature verification
- on location fails, include more detailed error message
=> feat(core): Adds signed location support

.github/workflows/checks.yaml, Makefile
=> chore(ci): ⬆️ golangci-lint 1.61

service/authorization/authorization.go, service/logger/audit/getDecision.go, service/logger/audit/getDecision_test.go, service/logger/audit/logger_test.go
resolves https://github.com/opentdf/platform/issues/1488
=> feat(core): Add entity category to audit logs

service/policy/db/namespaces.go, service/policy/namespaces/namespaces.go
closes #1426 
part 2 of 1426, addressing minor code cleanup and:
- architecture decisions per [adr readme
](https://github.com/opentdf/platform/blob/main/service/policy/adr/0000-current-state.md)
- recent audit improvements
=> feat(policy): 1426 tech debt migrate Namespace object queries to sqlc - PART 2

service/policy/db/key_access_server_registry.go, service/policy/db/query.sql, service/policy/db/query.sql.go, service/policy/kasregistry/key_access_server_registry.go
=> feat(policy): 1618 update KAS CRUD to align with ADR decisions

service/integration/resource_mappings_test.go, service/internal/fixtures/policy_fixtures.yaml, service/policy/db/query.sql, service/policy/db/query.sql.go, service/policy/db/resource_mapping.go
=> feat(policy): 1580 Resource Mappings GET/LIST should provide attribute value FQNs in response

sdk/assertion.go, sdk/tdf.go, sdk/tdf_test.go, sdk/tdferrors.go
resolves https://github.com/opentdf/platform/issues/1564
=> feat(sdk): Expose error types for signature, assertion, and kas failures

service/internal/access/pdp.go, service/internal/access/pdp_test.go
=> fix(authz): Move logs containing subject mappings to trace level

service/internal/auth/casbin.go, service/internal/auth/casbin_test.go
fixes the attempted resolution of https://github.com/opentdf/platform/issues/1645
=> fix: use the right service namespace and update the tests

.github/workflows/checks.yaml
Reverts opentdf/platform#1587
resolves https://github.com/opentdf/platform/issues/1510
=> fix(ci):  Revert "Don't run tests for markdown changes"

.github/workflows/action-lint.yaml, .github/workflows/release-build.yaml
Builds a version docker image when a platform service release happens.
=> chore(ci): simple docker build on service release

release-please.json, sdk/version.go
I think these release-please options are relative to the component paths? I should have noticed the lack of change before approving the tag
*
=> fix(sdk): Version config fix

service/policy/CONTRIBUTING.md, service/policy/adr/0003-database-transactions.md, service/policy/db/README.md
* Adds a contributing guide to the various policy services linking to existing documentation as appropriate or providing current conventions
=> chore(docs): policy service contribution docs

examples/cmd/isvalid.go, sdk/sdk.go
* Replaces isvalid example with a utility for checking isvalid on a file
=> chore(examples): Lets isvalid be useful

.github/workflows/release.yaml
=> chore(ci): Fix misspelling

.github/workflows/auto-approve-version-bumps.yaml, .github/workflows/friendly-reminders.yaml, .github/workflows/nightly-build.yaml, .github/workflows/traffic.yaml
- Quote variables appropriately
- be more careful on a few places that could have spaces
=> chore(ci): Fix actionlint failures

.github/workflows/sonarcloud.yml, .github/workflows/vulnerability-check.yaml
=> chore(ci): Use go 1.22.12 in vulncheck

test/start-up-with-containers/action.yaml
=> chore(ci): Fix missing option to workflow

test/start-up-with-containers/action.yaml
=> chore(ci): Fix wrong cwd in start-up-with-containers

.github/workflows/sonarcloud.yml
=> chore(ci): Updates renamed sonarcloud scan action

.github/workflows/checks.yaml
=> chore(ci): Let xtest focus on this sdk

.github/workflows/languagetool.yaml
=> chore: add languagetool for grammar and spellcheck

service/pkg/server/start.go, test/service-start.bats
=> fix(core): map IPC reauth routes config 

service/policy/db/migrations/20250402150650_key_management_update_timestamp.md, service/policy/db/migrations/20250402150650_key_management_update_timestamp.sql
1. Add timezone to key management tables.
2. Add expiration field to sym table
3. Add triggers to automatically update `updated_at` column/row
=> Dspx 647 migrate timestamps

.github/workflows/checks.yaml
=> chore(ci): Enable skew testing

.github/workflows/codeql.yaml
=> chore(ci): enable actions scanning with codeql

.github/workflows/action-lint.yaml
=> chore(ci): update deprecated input of fail_on_error to fail_level

.github/workflows/checks.yaml
=> chore(ci): fix benchmark tests permissions

.github/workflows/checks.yaml
- Okay I never did quite figure out what was wrong with the loop in the script so I just removed it.
=> chore(ci): replace busted but pretty job fail code

.github/workflows/checks.yaml
* add decision benchmarks
DSPX-1020
=> chore(ci):  run decision benchmark tests

Makefile
=> chore: update Makefile to leverage golangci-lint fmt

.github/dco.yaml, .github/dco.yml
=> chore: rename dco.yaml to dco.yml

.github/workflows/dco_merge_group.yaml
=> chore(ci): bypass dco check in merge queue

.golangci.yaml, service/authorization/authorization.go, service/integration/attribute_fqns_test.go, service/integration/attributes_test.go, service/integration/kas_registry_key_test.go, service/integration/kas_registry_test.go, service/integration/keymanagement_test.go, service/integration/namespaces_test.go, service/integration/resource_mappings_test.go, service/internal/auth/authn.go, service/internal/auth/casbin_test.go, service/internal/fixtures/fixtures.go, service/internal/security/in_process_provider.go, service/logger/audit/logger.go, service/trust/delegating_key_service.go
Adds the funcorder linter that I think my help keep code more readable. But open to feedback and we want to move forward with this do we want to enforce an alphabetical order?
https://github.com/manuelarte/funcorder
=> chore(core): add funcorder linter and updates service

service/pkg/server/start_test.go
* Expand test coverage around service registration
=> chore(core): Expand test coverage

.golangci.yaml, service/authorization/authorization.go, service/entityresolution/claims/claims_entity_resolution.go, service/entityresolution/keycloak/keycloak_entity_resolution.go, service/integration/attribute_fqns_test.go, service/integration/attributes_test.go, service/integration/kas_registry_test.go, service/integration/resource_mappings_test.go, service/internal/access/pdp.go, service/internal/auth/authn.go, service/internal/auth/authn_test.go, service/internal/auth/casbin.go, service/internal/auth/config.go, service/internal/security/in_process_provider.go, service/internal/security/standard_crypto.go, service/internal/server/memhttp/memhttp.go, service/kas/access/rewrap.go, service/pkg/db/db.go, service/pkg/db/db_migration.go, service/pkg/db/marshalHelpers.go, service/pkg/server/start_test.go, service/pkg/serviceregistry/serviceregistry.go, service/policy/db/attributes.go, service/policy/db/key_access_server_registry.go, service/rttests/rt_test.go, service/tracing/otel.go
This pull request introduces the [perfsprint](https://github.com/catenacyber/perfsprint) linter and fixes issues in the service module.
=> chore(core): enable perfsprint linter and fix issues in service

.policy.yml
=> chore(ci): increase modified_lines and try to ignore gen files

service/README.md, service/pkg/server/options.go, service/pkg/serviceregistry/serviceregistry.go
* Expand comments around service registration
=> chore(core): Expand mode explanation

.github/workflows/label.yaml
=> chore(ci): pr size labeler needs issues:write

.github/workflows/label.yaml, .policy.yml
chore(ci): add external contributors approval rule
*
=> chore(ci): move to labels to flag large pull requests

README.md, docker-compose.yaml, run-compose.sh
* Add compose script to make running on M4 chips easier
=> chore(core): add command to handle variance in env variables for M4 chips

service/go.mod, service/go.sum
1.) Update protocol go in service.
=> chore(deps): update protocol go in service to v0.3.6

service/policy/db/attribute_fqn.go, service/policy/db/attributes.go, service/policy/db/grant_mappings.go, service/policy/db/grant_mappings_test.go
=> feat(policy): map and merge grants and keys

.github/workflows/release-build.yaml
* Use correct bash quoting and escaping for scripts to use trivy and cosign for image reports and attestated SBOMs
=> fix(ci): Fixes issues in attested docker builds

service/pkg/server/options.go
* More concise for the more common variant of a single trust provider
=> feat(core): Prefers an ellipsized version

.github/workflows/reusable_backport.yaml
=> chore(ci): Use GitHub app token for backport action

release-please_main-branch.json
=> chore(ci): only bump minor on main

.github/workflows/reusable_backport.yaml
=> chore(ci): set backport to open draft pr's on conflicts

.github/workflows/checks.yaml, .github/workflows/vulnerability-check.yaml, examples/go.mod, go.work, lib/fixtures/go.mod, lib/ocrypto/go.mod, protocol/go/go.mod, sdk/go.mod, service/go.mod
* example failure: https://github.com/opentdf/platform/actions/runs/15592986986
* Successful run: https://github.com/opentdf/platform/actions/runs/15595629949
* Addresses: https://pkg.go.dev/vuln/GO-2025-3751
=> chore(ci): Update target toolchain for govulncheck

sdk/granter.go, sdk/granter_test.go, sdk/resource_locator.go, sdk/tdf.go, sdk/tdf_config.go
=> feat(sdk): autoconfig kaos with kids

sdk/assertion.go, sdk/tdf.go, sdk/tdf_config.go, sdk/tdf_config_test.go, sdk/tdf_test.go
=> feat: add system metadata assertions to TDFConfig

.github/workflows/label.yaml
=> chore(ci): need github app token to call org members api

.github/workflows/pr-checks.yaml
https://regex101.com/r/vkijKf/1/
=> chore(ci): add regex release branch scope

service/internal/access/v2/pdp.go
* Fixes one direct access of proto fields without using nil-safe getter
=> fix(authz): access pdp should use proto getter

.github/workflows/checks.yaml
* Recent API work to add sensible limits in auth service v2 requires a downstream fix in CI
=> chore(ci): benchmarking bulk decisioning should comply with API upper bound limits

sdk/go.mod, sdk/go.sum
=> feat(sdk): bump protocol/go v0.6.0

.github/workflows/checks.yaml, service/internal/auth/casbin.go, service/pkg/server/options.go, service/pkg/server/start.go
=> fix(core): resolve 'built-in' typos

.github/workflows/checks.yaml
=> fix(core): Attempt to fix shellcheck

service/policy/db/models.go
These changes originally showed up in #2601.
=> fix: updated generated sqlc

service/internal/auth/discovery.go
* Include userinfo endpoint in our WellKnownConfig response.
=> chore(core): include userinfo endpoint in well known response.

service/internal/server/server.go
1.) Bump default write timeout to 10 seconds.
=> feat(core): Bump default write timeout.
